//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StableNotes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int ActionId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public string Note { get; set; }
        public Nullable<int> HorseId { get; set; }
        public Nullable<int> HoofingId { get; set; }
        public Nullable<int> FoodsupplementId { get; set; }
        public Nullable<int> FoodId { get; set; }
        public Nullable<int> CareId { get; set; }
        public Nullable<int> MedicineId { get; set; }
        public Nullable<int> TrainingId { get; set; }
    
        public virtual Horse Horse { get; set; }
        public virtual Hoofing Hoofing { get; set; }
        public virtual Foodsupplement Foodsupplement { get; set; }
        public virtual Food Food { get; set; }
        public virtual Care Care { get; set; }
        public virtual Medicine Medicine { get; set; }
        public virtual Training Training { get; set; }
    }
}
