//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StableNotes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public string ActionId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public string Note { get; set; }
        public string HorseId { get; set; }
        public string HoofingId { get; set; }
        public string FoodsupplementId { get; set; }
        public string FoodId { get; set; }
        public string CareId { get; set; }
        public string MedicineId { get; set; }
        public string TrainingId { get; set; }
    
        public virtual Horse Horse { get; set; }
        public virtual Hoofing Hoofing { get; set; }
        public virtual Foodsupplement Foodsupplement { get; set; }
        public virtual Food Food { get; set; }
        public virtual Care Care { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
