//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StableNotes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoofing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hoofing()
        {
            this.Action = new HashSet<Action>();
        }
    
        public int HoofingId { get; set; }
        public string Frontshoe { get; set; }
        public string Frontsize { get; set; }
        public string Frontangle { get; set; }
        public string Frontlength { get; set; }
        public string Backshoe { get; set; }
        public string Backsize { get; set; }
        public string Backangle { get; set; }
        public string Backlength { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action> Action { get; set; }
    }
}
