//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StableNotes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Horse()
        {
            this.Action = new HashSet<Action>();
        }
    
        public int HorseId { get; set; }
        public string Name { get; set; }
        public string Registernumber { get; set; }
        public string URL { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string StableId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action> Action { get; set; }
        public virtual Stable Stable { get; set; }
        public virtual Person Person { get; set; }
        public virtual User User { get; set; }
    }
}
