//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StableNotes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Horse()
        {
            this.Action = new HashSet<Action>();
        }
    
        public string HorseId { get; set; }
        public string Horsename { get; set; }
        public string Horseregisternumber { get; set; }
        public string HorseURL { get; set; }
        public string Horsenote { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string StableId { get; set; }
        public string PersonId { get; set; }
        public string UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action> Action { get; set; }
        public virtual Stable Stable { get; set; }
    }
}
