//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StableNotes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kauppeedbEntities : DbContext
    {
        public kauppeedbEntities()
            : base("name=kauppeedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Care> Care { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<Foodsupplement> Foodsupplement { get; set; }
        public virtual DbSet<Hoofing> Hoofing { get; set; }
        public virtual DbSet<Horse> Horse { get; set; }
        public virtual DbSet<Medicine> Medicine { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Phone> Phone { get; set; }
        public virtual DbSet<Stable> Stable { get; set; }
        public virtual DbSet<Training> Training { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
